### ISSUE TITLE
exception after running $ rnpm link

### ISSUE THREAD

**Issue by delfrrr** [Kennytian/react-native-instabug#14]
Hi! After running `$ rnpm link` I see this exception

```
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/delfrrr/dev/zowninative/node_modules/react-native-instabug/scripts/postlink/run'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
/Users/delfrrr/.nvm/versions/node/v4.4.0/lib/node_modules/rnpm/src/makeCommand.js:19
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-instabug/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/delfrrr/.nvm/versions/node/v4.4.0/lib/node_modules/rnpm/src/makeCommand.js:19:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

**Comment by Kennytian** [comment]
@delfrrr  I am not sure this issue it's latest rnpm bug or me, Microsoft's react native code push had same issue too. 

But good news is only show an exception message, actually package rnpm linked successful, yes?

**Comment by delfrrr** [comment]
Yeah, it looks ok after linking. But I didn't really used it, since I need ios.

**Comment by Kennytian** [comment]
@delfrrr  We need a iOS contributor, welcome you recommend one to me 💯 👍
